title: Programiranje
description: Meterijali uz vježbe na kolegiju Programiranje
remote_theme: just-the-docs/just-the-docs

# This tells the theme to look for your custom.scss
search_enabled: true

# Setup for local development
url: "https://KgeoZg.github.io"
baseurl: "/Programiranje" 

plugins:
  - jekyll-sass-converter
  - jekyll-remote-theme

favicon_ico: "assets/images/GF logo.svg"

aux_links: {}